image: docker:stable

variables:
    IMAGE_NAME: "php-common:8.1"

services:
    - docker:20.10.16-dind

build_image:
    script:
        - docker build -t vziks/$IMAGE_NAME .
        - docker login -u vziks -p $DOCKER_HUB_TOKEN
        - docker push vziks/$IMAGE_NAME

