image: docker:stable

variables:
    IMAGE_NAME: "php-common:8.1"

services:
    - docker:24.0.7-dind

build_image:
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:;CI_COMMIT_TAG
    script:
#        - echo "$CI_REGISTRY_USER"
#        - echo "$CI_REGISTRY_PASSWORD"
#        - echo "$CI_REGISTRY"
#        - echo "$CI_REGISTRY_IMAGE"
        - docker build -t vziks/$IMAGE_NAME .
        - docker login -u vziks -p $DOCKER_HUB_TOKEN
        - docker push vziks/$IMAGE_NAME

        - docker build -t $CI_REGISTRY_IMAGE .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - echo $IMAGE_TAG
        - echo $CI_COMMIT_TAG
        - docker push $IMAGE_TAG